### ISSUE TITLE
LiveScript 1.4

### ISSUE THREAD

**Issue by icflorescu** [quarterto/liveify#9]
LiveScript 1.4 was [published](https://www.npmjs.com/package/livescript) on npm yesterday under a new name, all small caps.

I'm thinking, maybe you should publish `liveify@3` with a `"livescript": "^1.4.0"` dependency...

Any thoughts?

**Comment by unclechu** [comment]
@icflorescu no! Don't to it! It's very dangerous! Because LiveScript doesn't follow semver, and it will kill backward compatibility. We should use only specific version of livescript, like "1.4.0", not "1.4.x"/"~1.4.0" or especially  "^1.4.0"/"1.x".

You can ignore me, but when you will deploy your project next time with lot of errors or just unexpected behavior, you'll remember this.

Also, I'm using this own fork: https://github.com/unclechu/liveify-stable for control version of LiveScript by myself by "peerDependencies". Maintainer of `liveify` said that it's just bad way, because it looks like a some sort of hack, but for production it's only adequate solution.

**Comment by icflorescu** [comment]
@unclechu I understand the risks, but even using your fork, one would only be able to use LiveScript **up to 1.3.1**, now that livescript package name became **all-small-caps**.

LiveScript doesn't follow semver, but it looks like breaking changes only appear between minor versions (i.e. 1.4.0 is not backwards-compatible with 1.3.0, but 1.3.1 is).

In which case, maybe `liveify@3` should start with `"livescript": "1.4.x"` and we'll see what happens when livescript reaches 1.5.

The whole situation is far from ideal, I know, but so is having lots of similar packages in the public npm registry...

**Comment by unclechu** [comment]
Good news, @gkz said that after 1.4.0 LS he'll not break backward compatibility:
https://github.com/gkz/LiveScript/issues/723#issuecomment-102450826

**Comment by gkz** [comment]
I added a pull request, #9

1.4.0 is backwards compatible with 1.3.X (other than the module name change forced upon us by npm), and I will not make any further breaking changes on the 1.X line.

The only possible change in 1.4 is that generators auto-return by default. People using generators don't usually rely on the return value (when `generator.next().done == true`, the return value sets `generator.next().value`), and the only change here is that rather than always being null, it now gets the return value.

**Comment by quarterto** [comment]
@gkz could you publish old (pre-1.4) versions under the new name? Otherwise there's no easy way for libraries like `liveify` to upgrade and still allow old versions.

**Comment by quarterto** [comment]
ok, so I'm deprecating this package in favour of [Anyify](https://github.com/quarterto/Anyify). you can install whatever version of livescript you want and run `browserify -t [ anyify --ls [ livescript?compile ] ]`.
